services:
  - type: web
    name: bhm-b2b-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push --accept-data-loss && node -r ts-node/register src/server.ts
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: TS_NODE_TRANSPILE_ONLY
        value: "true"
